CREATE OR ALTER PROC USP_INSERT_CANDIDATE_INFORMATION
(
	@FIRST_NAME VARCHAR(250),
	@LAST_NAME VARCHAR(250),
	@PHONE_NUMBER VARCHAR(250),
	@EMAIL VARCHAR(250),
	@LINKEDIN_PROFILE VARCHAR(250),
	@GITHUB_PROFILE VARCHAR(250),
	@TIME_TO_CONTACT VARCHAR(250),
	@REMARKS VARCHAR(MAX)
)

AS
BEGIN
	IF EXISTS(SELECT TOP 1 1 FROM CANDIDATE_INFORMATION WHERE ISNULL(EMAIL,'')=@EMAIL)
	BEGIN
	
		UPDATE CANDIDATE_INFORMATION SET 
			FIRST_NAME=@FIRST_NAME ,
			LAST_NAME=@LAST_NAME ,
			PHONE_NUMBER =@PHONE_NUMBER,
			LINKEDIN_PROFILE =@LINKEDIN_PROFILE,
			GITHUB_PROFILE=@GITHUB_PROFILE,
			TIME_TO_CONTACT=@TIME_TO_CONTACT,
			REMARKS=@REMARKS
			WHERE EMAIL=@EMAIL
	END
	ELSE
	BEGIN
		INSERT INTO CANDIDATE_INFORMATION (	
			FIRST_NAME ,
			LAST_NAME ,
			PHONE_NUMBER ,
			EMAIL,
			LINKEDIN_PROFILE ,
			GITHUB_PROFILE,
			TIME_TO_CONTACT,
			REMARKS
			)
		VALUES
		(
			@FIRST_NAME ,
			@LAST_NAME ,
			@PHONE_NUMBER ,
			@EMAIL,
			@LINKEDIN_PROFILE ,
			@GITHUB_PROFILE,
			@TIME_TO_CONTACT,
			@REMARKS
		)
	END
END

