USE [CANDIDATE_DB]
GO

/****** Object:  Table [dbo].[CANDIDATE_INFORMATION]    Script Date: 12/24/2024 12:13:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CANDIDATE_INFORMATION](
	[TRAN_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](250) NULL,
	[LAST_NAME] [varchar](250) NULL,
	[PHONE_NUMBER] [varchar](250) NULL,
	[EMAIL] [varchar](250) NULL,
	[LINKEDIN_PROFILE] [varchar](250) NULL,
	[GITHUB_PROFILE] [varchar](250) NULL,
	[TIME_TO_CONTACT] [varchar](250) NULL,
	[REMARKS] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[TRAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


